### ISSUE TITLE
cant run the code

### ISSUE THREAD

**Issue by cotone1807** [fastuptime/Whatsapp_Bulk_Message_And_Picture_Sending#1]
D:\whatsapp\Whatsapp_Bulk_Message_And_Picture_Sending\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (D:\whatsapp\Whatsapp_Bulk_Message_And_Picture_Sending\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at D:\whatsapp\Whatsapp_Bulk_Message_And_Picture_Sending\node_modules\whatsapp-web.js\src\Client.js:744:36      
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.12.2

**Comment by codedByCan** [comment]
Update modules
